global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 30s
  repeat_interval: 1m
  # group_wait: 30s
  # group_interval: 5m
  # repeat_interval: 1h
  # receiver: 'default-receiver'
  receiver: 'telegram'

receivers:
  # - name: 'default-receiver'
  - name: 'telegram'
    telegram_configs:
    - api_url: https://api.telegram.org
      # bot_token: ${BOT_TOKEN}
      bot_token: 7716148114:AAGERVb_Jt61Hro_0p6yYVHy_JROxQmKj7E
      chat_id: -1002865715313
      # parseMode: 'MarkdownV2' # The template I provide is in Markdown Mode
      # disableNotifications: false
      # sendResolved: true