global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 30s
  repeat_interval: 1m
  # group_wait: 30s
  # group_interval: 5m
  # repeat_interval: 1h
  # receiver: 'default-receiver'
  receiver: 'telegram'

receivers:
  # - name: 'default-receiver'
  - name: 'telegram'
    telegram_configs:
      - chat_id: -1002865715313
        bot_token_file: /opt/telegram.token
        parse_mode: 'HTML'
        message: '{{ template "telegram.message". }}' 
        # api_url: https://api.telegram.org
        # bot_token: BOT_TOKEN
        # disableNotifications: false
        # sendResolved: true

templates:
  - '/etc/alertmanager/config/telegram.tmpl'     